# Generated by Django 5.2 on 2025-05-10 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='doctorupload',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='center',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='institute_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='institute_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorupload',
            name='status',
            field=models.CharField(choices=[('Unreported', 'Unreported'), ('Draft', 'Draft'), ('Reviewed', 'Reviewed'), ('Reported', 'Reported')], default='Unreported', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_part',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.center'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='modality',
            field=models.CharField(choices=[('CT', 'CT'), ('US', 'US'), ('XA', 'XA'), ('SC', 'SC'), ('AN', 'AN'), ('RF', 'RF'), ('OT', 'OT'), ('MR', 'MR'), ('CR', 'CR'), ('NM', 'NM'), ('PT', 'PT'), ('DX', 'DX'), ('PX', 'PX')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reported_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
