# Generated by Django 5.2 on 2025-05-10 10:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_center_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctorupload',
            name='dicom_file',
        ),
        migrations.AddField(
            model_name='doctorupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='dicom_file',
            field=models.FileField(blank=True, null=True, upload_to='dicoms/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_part',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.center'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='modality',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
